global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "keeper"
    static_configs:
      - targets: ['keeper:8081']
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: "kafka-jmx"
    static_configs:
      - targets: ['kafka:7071']